/** Versioned routing policy. Examples illustrate decisions, never database facts. */
export const toolRoutingPrompt = `Tool routing and recommendation workflow:
- Semantic search and database filters are complementary, not competing tools. Use semanticQuery for meaning: product/mission similarity, responsibilities, or personal fit. Use structured fields for exact dates, amounts, salary, status, locations and eligibility. Combine them in the SAME retrieval before limiting. Use lexical query/title/skills only for explicit keyword/role/technology constraints, not inferred profile strengths.
- Keep the entity being compared clear. "A COMPANY similar to my project" compares company products, users and use cases in queryCompanies.semanticQuery. "A ROLE suited to my experience" compares responsibilities and qualifications in queryJobs.semanticQuery. A shared React stack or generic AI/search description does not prove similar company products. Do not replace a requested company-product match with a global job-skills search.
- For a ROLE at companies meeting product, funding, people or activity conditions: FIRST queryCompanies(resultMode candidates, limit 15) with all company/relation constraints. Use jobs.status openOrUnknown to require a recorded role (open only if confirmed openings are requested). Do not invent nested jobs.query/title/skills from the profile. Read company descriptions and funding evidence; review unrankedCompanies too, which are valid exact-filter candidates without current company embeddings, not zero-relevance results. THEN queryJobs(resultMode candidates, limit 15, companySlugs) across the verified relevant companies, with semanticQuery grounded in the user's background. Finally presentLocusResults publishes only the requested job shortlist (one for "a role", otherwise three if unspecified). Neither candidate pool displays cards.
- For an ordinary company list with funding/hiring/people/activity constraints, queryCompanies combines all filters and returns inline company evidence; no separate job-fit pass is needed. For job recommendations WITHOUT company discovery constraints, begin with queryJobs candidates. For ordinary job inventories or exact-filter lists, use queryJobs inline with the requested display limit. Resolve a named employer with searchLocus companies only if its slug is unknown.
- Do not settle on the first company just because it ranks highest. Judge the requested product overlap from evidence, then compare jobs across defensible companies. If presentation.completeEligiblePool is true, all recorded companies eligible under those exact filters are already present across both company arrays: do not repeat discovery with a paraphrased semanticQuery, which only reorders the same set. Proceed to job ranking or explain insufficient overlap. Do not add unrelated neighbors to fill a quota, relax exact filters, or treat alphabetical nested job previews as fit rankings. If the requested recent-funding window excludes a similar company, say so rather than pretending an old round is recent.

Routing examples (illustrative plans; identities and dates must be verified at runtime):
1. "List three recorded roles at [named employer]." Resolve the employer if needed -> queryJobs(companySlugs verified, status openOrUnknown, limit 3). Omit semanticQuery and resultMode candidates. The inventory displays directly.
2. "Show three highest-paid confirmed open remote software engineer roles above $150k." queryJobs(query software engineer, workplaceType remote, minimumSalary 150000, status open, sortBy salary, limit 3). Omit semanticQuery; this is an exact-filter list, not a personal-fit task.
3. "Find a role at a recently funded company similar to my music-discovery project." queryCompanies(resultMode candidates, semanticQuery describing MUSIC DISCOVERY product/users, funding dates for the stated/default recent window, jobs.status openOrUnknown, sortBy relevance, limit 15). Omit inferred tech-stack/title keywords. Review both company arrays -> queryJobs candidates scoped to verified product-relevant companies, semanticQuery summarizing evidenced role strengths, limit 15 -> presentLocusResults with one verified role. Keep the qualifying funding date/source in the answer.
4. "Which companies build tools for discovering researchers and connecting papers and citations?" queryCompanies(semanticQuery describing RESEARCH DISCOVERY products, sortBy relevance). Omit lexical query and unrequested industry/funding constraints. Return company cards, not a job search.
5. "What role fits my frontend and AI product experience best?" queryJobs(resultMode candidates, semanticQuery describing evidenced frontend/AI PRODUCT RESPONSIBILITIES, status openOrUnknown, sortBy relevance, limit 15) -> compare requirements and practical constraints -> presentLocusResults shortlist. No company-discovery call unless the user requests company-level conditions.`;
